-- 코드를 작성해주세요
SELECT a.ID ID, 
       CASE WHEN a.PERCENT <=0.25 THEN 'CRITICAL'
            WHEN a.PERCENT <=0.50 THEN 'HIGH'
            WHEN a.PERCENT <=0.75 THEN 'MEDIUM'
            ELSE 'LOW' END COLONY_NAME
FROM (SELECT ID, 
             PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC
                                  ROWS BETWEEN UNBOUNDED PRECEDING 
                                  AND UNBOUNDED FOLLOWING) PERCENT
      FROM ECOLI_DATA) a
ORDER BY ID;