-- 코드를 입력하세요
SELECT a.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
       ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_INFO a
INNER JOIN REST_REVIEW b
ON a.REST_ID = b.REST_ID
WHERE ADDRESS LIKE CONCAT('서울','%')
GROUP BY a.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC
