-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
       GENDER, COUNT(DISTINCT(USER_ID)) USERS
FROM (SELECT SALES_DATE, GENDER, i.USER_ID USER_ID
    FROM USER_INFO i
    JOIN ONLINE_SALE s
    ON i.USER_ID = s.USER_ID
    WHERE GENDER IS NOT NULL) a
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;

