SELECT a.CAR_ID, ROUND(AVG(a.RENT_PERIOD),1) AVERAGE_DURATION
FROM (SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 RENT_PERIOD
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) a
GROUP BY a.CAR_ID
HAVING ROUND(AVG(a.RENT_PERIOD),1) >= 7
ORDER BY AVERAGE_DURATION DESC, a.CAR_ID DESC;



