-- 코드를 입력하세요
SELECT YEAR, MONTH, CNT PURCHASED_USERS, ROUND(CNT/TOTAL,1) PURCHASED_RATIO
FROM (
    SELECT (SELECT COUNT(*) 
            FROM USER_INFO
            WHERE YEAR(JOINED) = '2021') TOTAL, 
    COUNT(DISTINCT(a.USER_ID)) CNT, 
    YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
    FROM ONLINE_SALE a
    INNER JOIN USER_INFO b
    ON a.USER_ID = b.USER_ID
    WHERE YEAR(b.JOINED) = '2021'
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
    ) b
ORDER BY YEAR, MONTH

    
    

    