-- 코드를 입력하세요
SELECT a.CAR_ID, IFNULL(AVAILABILITY, '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
LEFT JOIN (SELECT HISTORY_ID, CAR_ID, '대여중' AVAILABILITY
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
           WHERE '2022-10-16' >= START_DATE
           AND '2022-10-16'<= END_DATE) b
ON a.HISTORY_ID = b.HISTORY_ID
WHERE a.END_DATE >= '2022-10-16'
GROUP BY a.CAR_ID
ORDER BY a.CAR_ID DESC