-- 코드를 작성해주세요
SELECT a.QUARTER QUARTER, COUNT(a.ID) ECOLI_COUNT
FROM (SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q') QUARTER,
             ID
      FROM ECOLI_DATA) a
GROUP BY a.QUARTER
ORDER BY a.QUARTER