-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as J_TOTAL_ORDER FROM JULY GROUP BY FLAVOR) j
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.J_TOTAL_ORDER) DESC
LIMIT 3;