-- 코드를 입력하세요
SELECT a.LEVEL HOUR, IFNULL(b.COUNT,0) COUNT
FROM (WITH RECURSIVE A AS (
    SELECT 0 AS LEVEL
    UNION ALL
    SELECT 1+A.LEVEL
      FROM A
     WHERE A.LEVEL < 23
     )
    SELECT LEVEL
    FROM A) a
LEFT OUTER JOIN
     (SELECT HOUR(DATETIME) HOUR, COUNT(ANIMAL_ID) COUNT
      FROM ANIMAL_OUTS
      GROUP BY HOUR(DATETIME)) b
ON a.LEVEL = b.HOUR
ORDER BY a.HOUR;