-- 코드를 입력하세요
-- USED_GOODS_BOARD : 중고 거래 게시판 정보
-- USED_GOODS_USER : 중고 거래 게시판 사용자 정보

SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE)
FROM USED_GOODS_USER AS U
JOIN USED_GOODS_BOARD AS B
ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE) ASC;