-- 코드를 작성해주세요
WITH CTE as (
    SELECT CASE 
       WHEN SCORE >= 96 THEN 'S'
       WHEN SCORE >= 90 THEN 'A'
       WHEN SCORE >= 80 THEN 'B'
       ELSE 'C' END as GRADE, SCORE, EMP_NO
    FROM (SELECT EMP_NO, AVG(SCORE) SCORE
         FROM HR_GRADE
         GROUP BY EMP_NO) t
)

SELECT a.EMP_NO, EMP_NAME, GRADE,
       CASE
       WHEN GRADE = 'S' THEN SAL*0.2
       WHEN GRADE = 'A' THEN SAL*0.15
       WHEN GRADE = 'B' THEN SAL*0.1
       ELSE 0 END as BONUS
FROM HR_EMPLOYEES a
INNER JOIN CTE b
ON a.EMP_NO = b.EMP_NO
ORDER BY a.EMP_NO



# SELECT * FROM HR_GRADE;