# SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
# FROM 

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') DATE_FORMAT
FROM REST_REVIEW a
INNER JOIN (
        SELECT MEMBER_ID, 
               COUNT(REVIEW_ID) CNT, 
               RANK() OVER(ORDER BY COUNT(REVIEW_ID) DESC) RANKING
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
) b
ON a.MEMBER_ID = b.MEMBER_ID
INNER JOIN MEMBER_PROFILE c
ON a.MEMBER_ID = c.MEMBER_ID
WHERE b.RANKING = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;

