-- 코드를 작성해주세요 (SELF JOIN)
SELECT a.ID, a.GENOTYPE as GENOTYPE, b.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA a
LEFT OUTER JOIN ECOLI_DATA b
ON a.PARENT_ID = b.ID
WHERE a.GENOTYPE & b.GENOTYPE = b.GENOTYPE
ORDER BY a.ID;
