SELECT MCDP_CD 진료과코드, COUNT(PT_NO) 5월예약건수
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY MCDP_CD
ORDER BY 5월예약건수, 진료과코드;


# SELECT MCDP_CD 진료과코드, PT_NO, APNT_YMD, APNT_CNCL_YN, APNT_CNCL_YMD
# FROM APPOINTMENT;



