-- 코드를 작성해주세요

SELECT a.YEAR, (a.MAX-a.SIZE_OF_COLONY) YEAR_DEV, a.ID
FROM (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, SIZE_OF_COLONY, 
    MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) MAX,
    ID
    FROM ECOLI_DATA
     ) a
ORDER BY a.YEAR, YEAR_DEV
