-- 코드를 입력하세요
SELECT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단'
AND DATE_FORMAT(b.START_DATE,'%m') = '10'
GROUP BY a.CAR_ID
ORDER BY a.CAR_ID DESC;