-- 코드를 작성해주세요

SELECT b.ID, c.FISH_NAME, a.LENGTH
FROM (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) a
JOIN FISH_INFO b
ON a.FISH_TYPE = b.FISH_TYPE
AND b.LENGTH = a.LENGTH
JOIN FISH_NAME_INFO c
ON a.FISH_TYPE = c.FISH_TYPE

