-- 코드를 입력하세요
SELECT TITLE, B.BOARD_ID, REPLY_ID, 
C.WRITER_ID, C.CONTENTS, DATE_FORMAT(C.CREATED_DATE,'%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY C
ON B.BOARD_ID = C.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY C.CREATED_DATE, TITLE;