-- 코드를 작성해주세요
SELECT GRADE, ID, EMAIL
FROM (
    WITH CODES AS ( 
     SELECT (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') PyCode,
            (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') CsharpCode,
            (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') FrontCode FROM DUAL) 
    SELECT CASE 
           WHEN (SKILL_CODE & FrontCode) AND (SKILL_CODE & PyCode) THEN 'A'
           WHEN (SKILL_CODE & CsharpCode) THEN 'B'
           WHEN (SKILL_CODE & FrontCode) THEN 'C' 
           END GRADE, ID, EMAIL
    FROM DEVELOPERS
    CROSS JOIN CODES
) a
WHERE GRADE IN ('A','B','C')
ORDER BY GRADE, ID
